from __future__ import annotations
import typing
__all__: list[str] = ['ComplexNumber', 'approximated_exp', 'exp']
class ComplexNumber:
    __hash__: typing.ClassVar[None] = None
    @typing.overload
    def __add__(self, other: ComplexNumber) -> ComplexNumber:
        ...
    @typing.overload
    def __add__(self, number: typing.SupportsFloat | typing.SupportsIndex) -> ComplexNumber:
        ...
    def __eq__(self, other: ComplexNumber) -> bool:
        ...
    def __init__(self, re: typing.SupportsFloat | typing.SupportsIndex, im: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __mul__(self, other: ComplexNumber) -> ComplexNumber:
        ...
    @typing.overload
    def __mul__(self, number: typing.SupportsFloat | typing.SupportsIndex) -> ComplexNumber:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def im(self) -> float:
        ...
    @property
    def norm(self) -> float:
        ...
    @property
    def re(self) -> float:
        ...
def approximated_exp(z: ComplexNumber, iteration: typing.SupportsInt | typing.SupportsIndex = 5) -> ComplexNumber:
    ...
def exp(z: ComplexNumber) -> ComplexNumber:
    ...
__version__: str = '0.1.0'
